env:
  type: "frankarobot"
  resources_dir: "../data/resources"
  object_centers: {'HUMAN_CENTER': [-0.2, -0.6, 0.9], 'LAPTOP_CENTER': [-0.4, 0.0, 0.635]}
  horizon: 10
  timestep: 0.5
  trajset_file: "../data/traj_sets/frankarobot_1000.npy"
  per_SG: 10
  train_test_split: 0.8
  real: False

  input_dict: {'lowdim': False, 'EErot': False, 'noxyz': False, 'norot': False, 'noangles': True} # TODO make sure to disable for 2